# 学科标签配置
[subjects]
math = "数学"
physics = "物理"
chemistry = "化学"
biology = "生物"
chinese = "语文"
english = "英语"
politics = "政治"
history = "历史"
geography = "地理"
informatics = "信息"

# 知识点标签配置
[knowledge_points]
# 数学知识点
math = [
    "函数与导数", "三角函数", "数列", "概率与统计", "立体几何", 
    "平面解析几何", "复数", "算法与框图", "排列组合", "不等式",
    "集合", "逻辑", "矩阵与行列式", "向量", "参数方程",
    "极坐标", "曲线与曲面", "数系", "方程", "函数",
    "数列", "导数", "微分", "积分", "立体几何", 
    "解析几何", "坐标系", "三视图", "直线与圆", "椭圆",
    "双曲线", "抛物线", "曲线与切线", "统计", "计数原理"
]

# 物理知识点
physics = [
    "力学", "热学", "电磁学", "光学", "原子物理", 
    "相对论", "量子力学", "机械波", "电磁波", "振动",
    "力与运动", "牛顿运动定律", "万有引力", "动能与势能",
    "动量与碰撞", "角动量", "流体力学", "气体定律",
    "热力学第一定律", "热力学第二定律", "静电场", "电容",
    "电流与电路", "磁场", "电磁感应", "交变电流",
    "电磁振荡", "光的反射", "光的折射", "光的干涉",
    "光的衍射", "光的偏振", "光电效应", "波粒二象性"
]

# 化学知识点
chemistry = [
    "原子结构", "元素周期律", "化学键", "物质结构", "氧化还原反应",
    "电化学", "化学平衡", "化学反应速率", "酸碱平衡", "溶液",
    "胶体", "电解质", "非电解质", "气体", "固体",
    "热化学", "化学能", "有机化学", "烃", "醇酚醛",
    "羧酸", "酯", "卤代烃", "胺", "杂环化合物",
    "糖类", "氨基酸", "蛋白质", "脂类", "核酸",
    "高分子化合物", "聚合反应", "单质", "金属化合物", "非金属化合物"
]

# 生物知识点
biology = [
    "细胞结构", "细胞生理", "物质运输", "酶", "细胞呼吸",
    "光合作用", "遗传", "基因", "蛋白质合成", "变异",
    "DNA复制", "有丝分裂", "减数分裂", "生物进化", "生态系统",
    "种群", "群落", "生物多样性", "植物激素", "动物激素",
    "神经调节", "免疫", "体液调节", "生殖", "发育",
    "人体解剖", "人体生理", "植物解剖", "植物生理", "微生物",
    "原核生物", "真核生物", "病毒", "生物技术", "基因工程"
]

# 题型标签配置
[question_types]
choice = "选择题"
fill = "填空题"
calculation = "计算题"
proof = "证明题"
experimental = "实验题"
short_answer = "简答题"
comprehensive = "综合题"
reading = "阅读理解"
essay = "作文"
true_false = "判断题"

# 难度标签配置
[difficulties]
basic = "基础"
medium = "中等"
hard = "偏难"
very_hard = "困难"

# 作答状态标签配置
[answer_status]
correct = "正确"
incorrect = "错误"
partial = "部分正确"
blank = "未作答"

# 错因类型标签配置
[error_types]
none = "无"
calculation = "计算失误"
concept = "概念混淆"
formula = "公式错误"
logic = "逻辑错误"
reading = "审题不清"
steps = "步骤遗漏"
writing = "书写不规范"
understanding = "理解有误"

# 订正状态标签配置
[correction_status]
corrected = "有批改/订正痕迹"
uncorrected = "未订正"
no_need = "无需订正"