subjects = [
  "数学",
  "物理",
  "化学",
  "生物",
  "语文",
  "英语",
  "政治",
  "历史",
  "地理"
] 

# 知识点仍按学科分组，但只保留值数组
[knowledge_points]
math = [
  "集合",  "不等式", "基本不等式", "一元二次不等式", "绝对值不等式",
  "柯西不等式", "函数", "对勾函数", "一元二次函数", "抽象函数",
  "对数函数", "指数函数", "复合函数", "函数增长差异", "二分法",
  "对数", "指数", "同构", "三角函数", "任意角",
  "诱导公式", "三角恒等变换", "两角和与差公式", "积化和差", "和差化积",
  "数列", "等差数列", "等比数列", "递推数列", "数学归纳法",

  "向量", "数量积", "向量积", "空间直线", "空间平面",
  "立体几何", "概率论", "排列组合", "二项式定理", "线性代数",
  "矩阵", "行列式", "极限", "导数", "微分",
  "积分", "微积分基本定理", "偏导数", "多元函数", "复数",
  "解析几何", "圆锥曲线", "椭圆", "双曲线", "抛物线"
]

physics = [
  "质点参考系", "时间位移", "速度", "加速度",
  "匀变速直线运动", "自由落体", "重力", "弹力",
  "摩擦力", "牛顿第一定律", "牛顿第二定律", "牛顿第三定律",
  "力的合成与分解", "共点力平衡", "力学单位制", "超重与失重",
  "曲线运动", "运动的合成与分解", "平抛运动", "抛体运动",
  "圆周运动", "向心力", "向心加速度", "生活中的圆周运动",
  "行星的运动", "万有引力定律", "万有引力理论的成就", "宇宙航行",
  "功", "功率", "重力势能", "动能", "动能定理", "机械能守恒定律",
  "实验：验证机械能守恒定律"
]

chemistry = [
  "原子结构", "元素周期律", "化学键", "物质结构", "氧化还原反应",
  "电化学", "化学平衡", "化学反应速率", "酸碱平衡", "溶液",
  "胶体", "电解质", "非电解质", "气体", "固体",
  "热化学", "化学能", "有机化学", "烃", "醇酚醛",
  "羧酸", "酯", "卤代烃", "胺", "杂环化合物",
  "糖类", "氨基酸", "蛋白质", "脂类", "核酸",
  "高分子化合物", "聚合反应", "单质", "金属化合物", "非金属化合物"
]

biology = [
  "细胞结构", "细胞生理", "物质运输", "酶", "细胞呼吸",
  "光合作用", "遗传", "基因", "蛋白质合成", "变异",
  "DNA复制", "有丝分裂", "减数分裂", "生物进化", "生态系统",
  "种群", "群落", "生物多样性", "植物激素", "动物激素",
  "神经调节", "免疫", "体液调节", "生殖", "发育",
  "人体解剖", "人体生理", "植物解剖", "植物生理", "微生物",
  "原核生物", "真核生物", "病毒", "生物技术", "基因工程"
]

# 同样将其他映射改为列表，只保留值
question_types = [
  "选择题", "填空题", "计算题", "证明题", "实验题",
  "简答题", "综合题", "阅读理解", "作文", "判断题"
]

difficulties = [
  "基础", "中等", "偏难", "困难"
]

answer_status = [
  "正确", "错误", "部分正确", "未作答"
]

error_types = [
  "无", "计算失误", "概念混淆", "公式错误", "逻辑错误",
  "审题不清", "步骤遗漏", "书写不规范", "理解有误"
]

correction_status = [
  "有批改/订正痕迹", "未订正", "无需订正"
]
