"""OopsNote Core — 数据层。

独立于任何 UI 框架，CLI / REST / MCP 均可复用。
"""

from .assets import AssetStore
from .app_settings import AppSettingsStore
from .batch_render import BatchSourceRenderer
from .models import (
    BatchCropRect,
    BatchProcessJob,
    BatchProcessSegmentState,
    BatchSegment,
    BatchSegmentPart,
    BatchSessionRecord,
    BatchSessionUpdateRequest,
    ContentFormat,
    DiagramCandidate,
    DiagramItem,
    DiagramRunMode,
    DiagramRunStep,
    DiagramSourceRegion,
    DiagramStatus,
    OcrPrintedContext,
    PaperDraft,
    PaperDraftCreateRequest,
    PaperDraftItem,
    PaperDraftUpdateRequest,
    Problem,
    ProblemMergeRecord,
    QuestionType,
    RunArtifact,
    RunPurpose,
    RunStatus,
    RunValidationError,
    SearchQuery,
    SolutionCandidate,
    StageRun,
    StageStatus,
    TagCreateRequest,
    TagDimension,
    TagItem,
    TagsResponse,
    TaskCreateRequest,
    TaskRecord,
    TaskRun,
    TaskStage,
    TaskStatus,
    VariationRequest,
)
from .search import Searcher
from .identity import problem_fingerprint
from .store import (
    BatchSessionStore,
    BatchProcessJobStore,
    PaperDraftStore,
    RunStore,
    StateConflict,
    StorageCorruptionError,
    TaskStore,
    ProblemMergeStore,
)
from .tags import TagStore
from .subjects import SUBJECT_ALIASES, canonical_subject, subjects_match
from .workspace import Principal, UserRole, WorkspaceContext, WorkspaceId
from .workspace_stores import WorkspaceStoreFactory, WorkspaceStores

__all__ = [
    "SUBJECT_ALIASES",
    "AppSettingsStore",
    "AssetStore",
    "BatchCropRect",
    "BatchProcessJob",
    "BatchProcessJobStore",
    "BatchProcessSegmentState",
    "BatchSegment",
    "BatchSegmentPart",
    "BatchSessionRecord",
    "BatchSessionStore",
    "BatchSessionUpdateRequest",
    "BatchSourceRenderer",
    "ContentFormat",
    "DiagramCandidate",
    "DiagramItem",
    "DiagramRunMode",
    "DiagramRunStep",
    "DiagramSourceRegion",
    "DiagramStatus",
    "OcrPrintedContext",
    "PaperDraft",
    "PaperDraftCreateRequest",
    "PaperDraftItem",
    "PaperDraftStore",
    "PaperDraftUpdateRequest",
    "Principal",
    "Problem",
    "ProblemMergeRecord",
    "ProblemMergeStore",
    "QuestionType",
    "RunArtifact",
    "RunPurpose",
    "RunStatus",
    "RunStore",
    "RunValidationError",
    "SearchQuery",
    "Searcher",
    "SolutionCandidate",
    "StageRun",
    "StageStatus",
    "StateConflict",
    "StorageCorruptionError",
    "TagCreateRequest",
    "TagDimension",
    "TagItem",
    "TagStore",
    "TagsResponse",
    "TaskCreateRequest",
    "TaskRecord",
    "TaskRun",
    "TaskStage",
    "TaskStatus",
    "TaskStore",
    "UserRole",
    "VariationRequest",
    "WorkspaceContext",
    "WorkspaceId",
    "WorkspaceStoreFactory",
    "WorkspaceStores",
    "canonical_subject",
    "problem_fingerprint",
    "subjects_match",
]
