"""OopsNote Core — 数据层。

独立于任何 UI 框架，CLI / REST / MCP 均可复用。
"""

from .assets import AssetStore
from .app_settings import AppSettingsStore
from .batch_render import BatchSourceRenderer
from .models import (
    BatchCropRect,
    BatchProcessJob,
    BatchProcessSegmentState,
    BatchSegment,
    BatchSegmentPart,
    BatchSessionRecord,
    BatchSessionUpdateRequest,
    ContentFormat,
    PaperDraft,
    PaperDraftCreateRequest,
    PaperDraftItem,
    PaperDraftUpdateRequest,
    Problem,
    QuestionType,
    RunStatus,
    SearchQuery,
    StageRun,
    StageStatus,
    TagCreateRequest,
    TagDimension,
    TagItem,
    TagsResponse,
    TaskCreateRequest,
    TaskRecord,
    TaskRun,
    TaskStage,
    TaskStatus,
)
from .search import Searcher
from .store import (
    BatchSessionStore,
    BatchProcessJobStore,
    PaperDraftStore,
    RunStore,
    StateConflict,
    StorageCorruptionError,
    TaskStore,
)
from .tags import TagStore

__all__ = [
    "AssetStore",
    "AppSettingsStore",
    "BatchSourceRenderer",
    "BatchCropRect",
    "BatchProcessJob",
    "BatchProcessJobStore",
    "BatchProcessSegmentState",
    "BatchSegment",
    "BatchSegmentPart",
    "BatchSessionRecord",
    "BatchSessionStore",
    "BatchSessionUpdateRequest",
    "ContentFormat",
    "PaperDraft",
    "PaperDraftCreateRequest",
    "PaperDraftItem",
    "PaperDraftStore",
    "PaperDraftUpdateRequest",
    "Problem",
    "QuestionType",
    "RunStatus",
    "RunStore",
    "StateConflict",
    "StorageCorruptionError",
    "Searcher",
    "SearchQuery",
    "StageRun",
    "StageStatus",
    "TagCreateRequest",
    "TagDimension",
    "TagItem",
    "TagsResponse",
    "TagStore",
    "TaskCreateRequest",
    "TaskRecord",
    "TaskRun",
    "TaskStage",
    "TaskStatus",
    "TaskStore",
]
