"""Backend module - auto-generated docstring."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol


class TaskRepositoryLike(Protocol):
    """Protocol for task repository dependency injection."""

    def list_all(self) -> dict[str, Any]: ...


class AgentSettingsLike(Protocol):
    """Protocol for agent settings service dependency injection."""

    def load_models(self) -> dict[str, str]: ...

    def save_models(self, models: dict[str, str] | None) -> dict[str, str]: ...

    def enabled_snapshot(self) -> dict[str, bool]: ...

    def save_enabled(self, enabled: dict[str, bool] | None) -> dict[str, bool]: ...

    def thinking_snapshot(self) -> dict[str, bool]: ...

    def save_thinking(self, thinking: dict[str, bool] | None) -> dict[str, bool]: ...

    def temperature_snapshot(self) -> dict[str, float]: ...

    def save_temperature(self, temperature: dict[str, float] | None) -> dict[str, float]: ...

    def resolve_temperature(self, agent: str) -> float | None: ...

    def load_gateway(self) -> Any: ...

    def save_gateway(self, settings: Any) -> Any: ...

    def load_debug(self) -> Any: ...

    def save_debug(self, settings: Any) -> Any: ...


class TasksServiceLike(Protocol):
    """Protocol for tasks service dependency injection."""

    def ensure_workers_started(self) -> None: ...
    def process_task(self, task_id: str, *, background: bool = ..., existing_problems: Any = ...) -> Any: ...
    def create_task(self, payload: Any, *, auto_process: bool = ...) -> Any: ...
    def upload_task(self, upload: Any, *, auto_process: bool = ...) -> Any: ...
    def get_task(self, task_id: str) -> Any: ...
    def iter_tasks(self) -> Any: ...
    def list_tasks(self) -> Any: ...
    def retry_task(self, task_id: str, *, background: bool = ...) -> Any: ...
    def cancel_task(self, task_id: str) -> None: ...
    def stream_events(self, task_id: str, last_id: str | None = ...) -> Any: ...
    def get_problems(self, task_id: str) -> Any: ...


class ModelsServiceLike(Protocol):
    """Protocol for models service dependency injection."""

    def prefetch_cache(self) -> None: ...


class AuthSettingsLike(Protocol):
    def load_registration(self) -> Any: ...

    def save_registration(self, enabled: bool) -> Any: ...


@dataclass
class BackendState:
    """Container for backend application state and services."""

    repository: TaskRepositoryLike
    ai_gateway_status: dict[str, object]
    agent_settings: AgentSettingsLike
    auth_settings: AuthSettingsLike
    tasks: TasksServiceLike
    models: ModelsServiceLike
